verbatim:
  cabal-version: 3.0

name:                bankroll
version:             1.3.3.0
github:              "natebragg/bankroll"
license:             BSD-3-Clause
author:              "Nate Bragg"
maintainer:          "nate@cs.tufts.edu"
copyright:           "(c) 2020 Nate Bragg"

extra-source-files:
- README.md

# Metadata used when publishing your package
synopsis:            Wrapper for COIN-OR CLP and CBC
category:            Numeric, Optimisation, Optimization

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/natebragg/bankroll#readme>

custom-setup:
  dependencies:
  - base >= 4.7 && < 5
  - Cabal >= 3.0
  - filepath

dependencies:
- base >= 4.7 && < 5

library:
  reexported-modules:
  - Numeric.Optimization.Bankroll.LinearFunction
  - Numeric.Optimization.Bankroll.Program
  - Numeric.Optimization.Bankroll.Pretty
  - Numeric.Optimization.Bankroll.Clp
  - Numeric.Optimization.Bankroll.Cbc
  dependencies:
  - bankroll-clp
  - bankroll-cbc

internal-libraries:
  bankroll-clp:
    source-dirs: src/clp
    verbatim:
      visibility: public
    reexported-modules:
    - Numeric.Optimization.Bankroll.LinearFunction
    - Numeric.Optimization.Bankroll.Program
    - Numeric.Optimization.Bankroll.Pretty
    exposed-modules:
    - Numeric.Optimization.Bankroll.Clp
    other-modules:
    - Bindings.Clp.Clp
    - Bindings.Clp.Managed
    dependencies:
    - bankroll-common
    extra-libraries:
    - Clp
  bankroll-cbc:
    source-dirs: src/cbc
    verbatim:
      visibility: public
    reexported-modules:
    - Numeric.Optimization.Bankroll.LinearFunction
    - Numeric.Optimization.Bankroll.Program
    - Numeric.Optimization.Bankroll.Pretty
    exposed-modules:
    - Numeric.Optimization.Bankroll.Cbc
    other-modules:
    - Bindings.Cbc.Cbc
    - Bindings.Cbc.Managed
    dependencies:
    - bankroll-common
    extra-libraries:
    - CbcSolver
  bankroll-common:
    source-dirs: src/common
    exposed-modules:
    - Numeric.Optimization.Bankroll.LinearFunction
    - Numeric.Optimization.Bankroll.Program
    - Numeric.Optimization.Bankroll.Pretty
    - Numeric.Optimization.Bankroll.Solver
    - Numeric.Optimization.Bankroll.Solver.Foreign
    - Numeric.Optimization.Bankroll.Topo
    other-modules:
    - Numeric.Algebra.Double
    dependencies:
    - algebra
    - mtl
    - pretty

executables:
  bankroll:
    main:                Main.hs
    generated-other-modules:
    - PackageInfo
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - bankroll
  lemonade:
    main: lemonade.hs
    source-dirs: examples/lemonade
    dependencies:
    - bankroll-clp

tests:
  bankroll-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - bankroll
    - QuickCheck
    - pretty
