verbatim:
  cabal-version: 3.0

name:                bankroll
version:             0.2.0.0
github:              "natebragg/bankroll"
license:             BSD-3-Clause
author:              "Nate Bragg"
maintainer:          "nate@cs.tufts.edu"
copyright:           "(c) 2020 Nate Bragg"

extra-source-files:
- README.md

# Metadata used when publishing your package
synopsis:            Wrapper for COIN-OR CLP
category:            Numeric, Optimisation, Optimization

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/natebragg/bankroll#readme>

custom-setup:
  dependencies:
  - base >= 4.7 && < 5
  - Cabal >= 3.0
  - filepath

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  exposed-modules:
  - Numeric.Optimization.Clp.Clp
  dependencies:
  - bankroll-clp
  - algebra
  - pretty

internal-libraries:
  bankroll-clp:
    source-dirs: src
    verbatim:
      visibility: public
    exposed-modules:
    - Numeric.Optimization.Clp.Clp
    - Numeric.Optimization.Clp.LinearFunction
    - Numeric.Optimization.Clp.Program
    - Numeric.Optimization.Clp.Pretty
    other-modules:
    - Bindings.Clp.Clp
    - Numeric.Optimization.Clp.Managed
    - Numeric.Algebra.Double
    - Data.Mapping
    dependencies:
    - algebra
    - pretty
    extra-libraries:
    - Clp

executables:
  bankroll:
    main:                Main.hs
    generated-other-modules:
    - PackageInfo
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - bankroll
  lemonade:
    main: lemonade.hs
    source-dirs: examples/lemonade
    dependencies:
    - bankroll-clp

tests:
  bankroll-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - bankroll
